### ISSUE TITLE
allow/deny loading of plugins

### ISSUE THREAD

**Issue by HeladoDeBrownie** [TrashMonks/Ereshkigal-Prime#53]
currently all files immediately inside `plugins/` are unconditionally loaded as plugins. the readme says to delete a plugin to prevent it from loading. this is unergonomic

try supporting two modes: "load all except", and "load only". this could be done something like

```toml
loadPluginsByDefault = true

[plugins]
unwanted-plugin = false
```

```toml
loadPluginsByDefault = false

[plugins]
wanted-plugin1 = true
wanted-plugin2 = true
```

it might make sense for the default to be to load only specified ones; this would be in line with how permissions are restrictive by default
